BEGIN;
CREATE TYPE app_module AS ENUM ('MONEY','SAFETY');
CREATE TYPE user_role AS ENUM ('ADMIN','MANAGER','ADVISOR','CLIENT');
CREATE TYPE case_state AS ENUM ('DRAFT','DISCOVERY','ANALYSIS','ASSESSMENT','REVIEW','PROPOSAL','PRESENTED','DECISION','ACCEPTED','CONTRACTING','AWAITING_PAYMENT','COMPLETED','FOLLOW_UP','DECLINED','CANCELLED');
CREATE TYPE assessment_status AS ENUM ('YES','NO','UNKNOWN','NOT_APPLICABLE');
CREATE TYPE proposal_state AS ENUM ('DRAFT','READY','PRESENTED','REVISION_REQUESTED','ACCEPTED','DECLINED','SUPERSEDED');
COMMIT;
